### ISSUE TITLE
tor: iptables with docker network_mode

### ISSUE THREAD

**Issue by tna76874** [retenet/tunle#3]
Hi,
thanks for your project - nice work. I played a bit with this image and experienced, that I only can access a webserver that is running on a separate service when I remove `:INPUT DROP [0:0]` from the v4 rules:https://raw.githubusercontent.com/retenet/tunle/master/iptables/v4/tor

I feel there must be a better way to allow access from the host OS to the docker image - but I'm not very familiar with the iptables rules. Do you have an idea?

Regards

**Comment by Wh1t3Fox** [comment]
Thanks! Are you trying to access a server running in Docker on the same host? Or are you trying to access a server you started within the Tor Docker image?

**Comment by tna76874** [comment]
Thank you for your reply. In fact, I want to access this docker image from the host machine (I use the network_mode of the tunnel docker container for another docker container).

**Comment by Wh1t3Fox** [comment]
Ahh okay, What are you exactly trying to access? If you want another container to use Tor you can use ```--net container:<docker_name>``` and they will be in the same namespace, transparently using Tor.

**Comment by tna76874** [comment]
That is what I'm doing. But then I cannot access the port mapped to the host machine. I'm trying to find an iptables rules to allow INPUT from the host machine.

**Comment by Wh1t3Fox** [comment]
I understand that, but what are you running on the port that you are mapping? The iptables are written as such to try and prevent any packet leakage from Tor. If you explain your setup details and goals I might be able to help solve the issue you are facing.

**Comment by tna76874** [comment]
It is just an regular webserver accessed from the host. But maybe any change in the iptables results in leakage - you are right.

**Comment by Wh1t3Fox** [comment]
If you are trying to access a webserver on your host from the Tor docker image it will not work (as you have seen) and I wouldn't suggest it either. You could setup ngrok or something similar for testing though
